FROM astral/uv:python3.12-bookworm-slim

WORKDIR /usr/src/app

COPY app.py pyproject.toml uv.lock .

RUN uv sync --no-dev --locked

EXPOSE 8501

CMD ["uv", "run", "streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
