events { worker_connections 1024; }

http {
	server {
    listen 8080;
    
    location /api/ {
      proxy_pass http://backend:8001;
    }
	}

  server {
    listen 8081;

    location / {
      proxy_pass http://inngest:8288;
    }
  }
}
